Use more modern PyGranta-style CI
ansys/grantami-bomanalytics pull request #509
Opened 2024-04-30 19:36 UTC by Andy-Grigg

Closes #487 

Use more PyAnsys actions in CI. These changes have largely been copied from the grantami-jobqueue repository.

2024-04-30 21:35 UTC, Andy-Grigg commented
I've checked the artifacts and they all look good. The docs look to have built correctly, including the examples.

2024-05-01 09:24 UTC, da1910 requested changes
One link, looks good otherwise

2024-05-01 09:24 UTC, da1910 commented on doc/source/conf.py
> +    "github_url": "https://github.com/ansys/grantami-jobqueue",
```suggestion
    "github_url": "https://github.com/ansys/grantami-bomanalytics",
```

2024-05-01 13:15 UTC, da1910 approved these changes

2024-05-01 13:53 UTC, da1910 commented on .github/workflows/ci_cd.yml
> -  merge_group:
We need this merge_group: trigger

2024-05-01 13:56 UTC, Andy-Grigg commented on .github/workflows/ci_cd.yml
> -  merge_group:
Thanks!

2024-05-01 14:07 UTC, merged